### ISSUE TITLE
How can I do a single level 2D inverse wavelet given four 2D ndarrays?

### ISSUE THREAD

**Issue by chesschi** [pierrepaleo/pypwt#1]
Let's say I have four numpy.ndarray cA, cH, cV and cD with shape (702, 1020) each and I would like to use pypwt to perform single level 2D inverse wavelet transform to recover an image.

    i = Wavelets(numpy.ndarray(1404, 2040), "haar", 1)
    i.coeffs[0] = cA
    i.coeffs[1][0] = cH
    i.coeffs[1][1] = cV
    i.coeffs[1][2] = cD
    i.inverse()
    scipy.misc.imsave("01.png", i.image.astype(numpy.uint8))

When I try to run the above line, it failed to recover the original image and the image is all black.

Please can you point out if I use pypwt correctly to perform inverse wavelet transform? Many thanks!

**Comment by pierrepaleo** [comment]
Hi @chesschi 
Have you tried

```python
W = Wavelets(numpy.zeros((1404, 2040)), "haar", 1)
# Coefficients are numbered as follows: [0: A, 1: H1, 2: V1, 3: D1,  4: H2, ...]
W.set_coeff(cA, 0, check=True) 
W.set_coeff(cH, 1, check=True)
W.set_coeff(cV, 2, check=True)
W.set_coeff(cD, 3, check=True)
W.inverse()
```
You can turn off `check=True` if the arrays are contiguous float32 with correct shape.

**Comment by chesschi** [comment]
It turns out to be insufficient GPU memory causing this problem. When I tried to create multiple instances of Wavelets objects, and if the GPU memory almost reaches the maximum, the Wavelets does not throw any error but produce black images.
