### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by monchin** [pierrepaleo/pypwt#3]
Hello, I'd like to use this package to accelerate my wavelet computation, but I got something wrong when I installed it. 
My environment:
OS: windows 10
python: 3.7.4

My installing step:
1. Install cuda 10.1 and cuDNN. I think I succeeded because after installation I input `nvcc -V`, and the information is:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:12:52_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.243
```
2. Clone this repository and `cd` into the directory.
3. Run `python setup.py install --user`

But  in this step, an error raised 
`OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME`

I opened `setup.py` to find the error, and then tried to print `os.environ`, there was no `CUDAHOME`. Then, in `setup.py`, I changed `CUDAHOME` to `CUDA_PATH`, which exists in `os.environ`, but another error raised 
`OSError: The CUDA nvcc path could not be located in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc`

So I searched `nvcc` in `C:\`, but I didn't find any subdir named `nvcc`. Instead there are `nvcc.exe`, `nvcc.NVX`, `nvcc.nvi`, `nvcc.profile` and so on.

Do you have any idea about that? Or if this package must be used on Linux or Mac OS? Thank you very much!

**Comment by pierrepaleo** [comment]
Hi @monchin, thanks for the report.

For some technical reasons, the current  `setup.py` does not support Windows. 
It has to be adapted to support the MSVC compiler. It is not trivial, as it entails digging inside `distutils`, but it looks like [cupy](https://github.com/cupy/cupy/blob/master/cupy_setup_build.py#L820) has a clean way to do it.

In the meantime, I advise you to use this package on Linux.

**Comment by monchin** [comment]
> Hi @monchin, thanks for the report.
> 
> For some technical reasons, the current `setup.py` does not support Windows.
> It has to be adapted to support the MSVC compiler. It is not trivial, as it entails digging inside `distutils`, but it looks like [cupy](https://github.com/cupy/cupy/blob/master/cupy_setup_build.py#L820) has a clean way to do it.
> 
> In the meantime, I advise you to use this package on Linux.

Thank you!

**Comment by Cibi075** [comment]
> Hello, I'd like to use this package to accelerate my wavelet computation, but I got something wrong when I installed it.
> My environment:
> OS: windows 10
> python: 3.7.4
> 
> My installing step:
> 
> 1. Install cuda 10.1 and cuDNN. I think I succeeded because after installation I input `nvcc -V`, and the information is:
> 
> ```
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2019 NVIDIA Corporation
> Built on Sun_Jul_28_19:12:52_Pacific_Daylight_Time_2019
> Cuda compilation tools, release 10.1, V10.1.243
> ```
> 
> 1. Clone this repository and `cd` into the directory.
> 2. Run `python setup.py install --user`
> 
> But in this step, an error raised
> `OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME`
> 
> I opened `setup.py` to find the error, and then tried to print `os.environ`, there was no `CUDAHOME`. Then, in `setup.py`, I changed `CUDAHOME` to `CUDA_PATH`, which exists in `os.environ`, but another error raised
> `OSError: The CUDA nvcc path could not be located in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc`
> 
> So I searched `nvcc` in `C:\`, but I didn't find any subdir named `nvcc`. Instead there are `nvcc.exe`, `nvcc.NVX`, `nvcc.nvi`, `nvcc.profile` and so on.
> 
> Do you have any idea about that? Or if this package must be used on Linux or Mac OS? Thank you very much!

Replace the path "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc" to "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" it worked for me.
