### ISSUE TITLE
Different threshold value

### ISSUE THREAD

**Issue by monchin** [pierrepaleo/pypwt#5]
Hello @pierrepaleo , I have learned the [tutorial](https://github.com/pierrepaleo/pypwt/blob/master/doc/denoising.rst), and I have a question: can I set different threhsold for each coefficient?
Actually, I read a [paper](https://odin.mdacc.tmc.edu/~jmorris/papers_files/denoisingSpectra-10feb04.pdf), and I'm trying to use the method in the paper, codes are [here](https://github.com/monchin/swt_denoise)
In the paper, the threshold are set to be a float times the median absolute deviation of each `D`, but in your tutorial, the threshold is set a fixed number.
Your doc said:
```
In [6]: w.hard_threshold?                                                       
Docstring:
Hard threshold the wavelets coefficients.
The hard thresholding is defined by

.. math::

    \text{HT}(x, t) = x \cdot 1_{|x| > t}

beta: float
    threshold factor
do_threshold_appcoeffs : int
    if not 0, the approximation coefficients will also be thresholded
Type:      builtin_function_or_method
```
I guess, maybe it would be better if  the threshold can be set to a list so each coefficient's threshold could be different?

**Comment by pierrepaleo** [comment]
Hi @monchin 

You are right, one threshold is defined for all the levels, i.e the coefficients arrays are thresholded with the same threshold. This can be implemented in the underlying `pdwt` library in `common.cu`: `w_call_soft_thresh`, `w_call_hard_thresh`, etc.

As a workaround, you can retrieve the wavelets coefficients, compute the threshold with numpy, threshold the coefficients on CPU, and set the new coefficients back to GPU. 
This is not optimal as it entails GPU<->CPU memory transactions, but in your case implementing MAD on GPU is tricky, so it would be done on CPU anyway.

Assuming the signal you want to analyze is one-dimensional:

```python
from pypwt import Wavelets
from scipy.stats import median_absolute_deviation

def hard_threshold(array, factor=0.67):
    # In-place hard threshold using factor * MAD
    mad = median_absolute_deviation(array)
    thresh = factor * mad
    mask = np.abs(array) <= thresh
    array[mask] = 0    

W = Wavelets(my_signal, "db8", nlevels)
W.forward()
coeffs = W.coeffs
for i in range(1, W.levels+1):
    hard_threshold(coeffs[i][0], factor=0.67)
    W.set_coeff(coeffs[i], i)
W.inverse()
```

**Comment by monchin** [comment]
> Hi @monchin
> 
> You are right, one threshold is defined for all the levels, i.e the coefficients arrays are thresholded with the same threshold. This can be implemented in the underlying `pdwt` library in `common.cu`: `w_call_soft_thresh`, `w_call_hard_thresh`, etc.
> 
> As a workaround, you can retrieve the wavelets coefficients, compute the threshold with numpy, threshold the coefficients on CPU, and set the new coefficients back to GPU.
> This is not optimal as it entails GPU<->CPU memory transactions, but in your case implementing MAD on GPU is tricky, so it would be done on CPU anyway.
> 
> Assuming the signal you want to analyze is one-dimensional:
> 
> ```python
> from pypwt import Wavelets
> from scipy.stats import median_absolute_deviation
> 
> def hard_threshold(array, factor=0.67):
>     # In-place hard threshold using factor * MAD
>     mad = median_absolute_deviation(array)
>     thresh = factor * mad
>     mask = np.abs(array) <= thresh
>     array[mask] = 0    
> 
> W = Wavelets(my_signal, "db8", nlevels)
> W.forward()
> coeffs = W.coeffs
> for i in range(1, W.levels+1):
>     hard_threshold(coeffs[i][0], factor=0.67)
>     W.set_coeff(coeffs[i], i)
> W.inverse()
> ```

Thank you, I got it.
